name: Deploy to EC2

# Triggers on push to the main branch
on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Use appleboy/scp-action to copy files to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOSTNAME }}          # Public IP or hostname of your EC2 instance
          username: ${{ secrets.EC2_USERNAME }}      # SSH username (e.g., ubuntu for Ubuntu instances)
          key: ${{ secrets.EC2_SSHKEY }}             # Private key (your .pem file) stored as a secret
          port: 22                                   # Default SSH port
          source: "./"                               # Files to copy (all files in the repo)
          target: "/home/ubuntu/"                    # Destination directory on the EC2 instance
