name: Deploy to EC2

# Triggers on push to the dev branch
on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 3: Run pytest to execute tests
      - name: Run tests
        run: |
          pytest -v tests/  # Run tests with verbose output

      # Step 4: Use appleboy/scp-action to copy files to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_NAME }}          # Public IP or hostname of your EC2 instance
          username: ${{ secrets.EC2_USERNAME }}      # SSH username (e.g., ubuntu for Ubuntu instances)
          key: ${{ secrets.EC2_SSHKEY }}             # Private key (your .pem file) stored as a secret
          port: 22                                   # Default SSH port
          source: "./"                               # Files to copy (all files in the repo)
          target: "/home/ubuntu/"                    # Destination directory on the EC2 instance
